line-length = 100

[lint]
select = ["ALL"]
ignore = [
    "ANN401",
    "COM812",
    "D100",
    "D101",
    "D102",
    "D103",
    "D107",
    "D202",
    "D203",
    "D213",
    "D419",
    "PERF203",
    "PLR",
    "RUF001",
    "RUF003",
    "SIM117",
    "T201",
]

[lint.isort]
lines-after-imports = 2
