[theme]
name = "nord-dark"

[theme.overrides]
idle_bg = "#2e3440fa"
idle_fg = "#d8dee9"
separator = " "
separator_bg = "#2e3440fa"
separator_fg = "#d8dee9"

[icons]
name = "awesome"

[[block]]
block = "focused_window"
max_width = 70
show_marks = "visible"

[[block]]
block = "sound"
step_width = 3
device_kind = "sink"
on_click = "gnome-control-center sound"

[block.theme_overrides]
idle_bg = "#8fbcbb"
idle_fg = "#2e3440"

[[block]]
block = "sound"
step_width = 3
device_kind = "source"
on_click = "gnome-control-center sound"

[block.theme_overrides]
warning_bg = "#8fbcbb"  # muted is OK
warning_fg = "#2e3440"  # muted is OK
idle_bg = "#ebcb8b"     # unmuted is warning
idle_fg = "#2e3440"     # unmuted is warning

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " {layout}"

[block.theme_overrides]
idle_bg = "#b48ead"
idle_fg = "#2e3440"

[block.mappings]
"English (US)" = "en"
"Ukrainian (N/A)" = "ua"

[[block]]
block = "net"
device = "enp38s0"
hide_inactive = true

[block.theme_overrides]
idle_bg = "#a3be86"
idle_fg = "#2e3440"

[[block]]
block = "net"
device = "wlo1"
format = "{ssid}"
hide_inactive = true

[block.theme_overrides]
idle_bg = "#a3be86"
idle_fg = "#2e3440"

[[block]]
block = "net"
device = "gpd0"
format = "VPN"
hide_inactive = true

[block.theme_overrides]
idle_bg = "#3b4252"

[[block]]
block = "battery"
format = "{percentage}"
hide_missing = true

[[block]]
block = "notify"

[block.theme_overrides]
idle_bg = "#3b4252"

[[block]]
block = "time"
interval = 60
format = "%b %d, %H:%M"
