[theme]
theme = "nord-dark"

[theme.overrides]
idle_bg = "#2e3440"
idle_fg = "#d8dee9"
separator_bg = { link = "idle_bg" }
separator_fg = { link = "idle_fg" }
separator = " "

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_width:70) | "

[[block]]
block = "sound"
max_vol = 100
device_kind = "sink"
headphones_indicator = true
theme_overrides.idle_bg = "#8fbcbb"
theme_overrides.idle_fg = { link = "idle_bg" }

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
max_vol = 100
device_kind = "source"
theme_overrides.idle_fg = { link = "warning_fg" }
theme_overrides.idle_bg = { link = "warning_bg" }
theme_overrides.warning_fg = { link = "idle_fg" }
theme_overrides.warning_bg = { link = "idle_bg" }

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "net"
device = "enp38s0"
format = " $icon ^icon_net_down{$speed_down.eng(p:K, u:b)} ^icon_net_up $speed_up.eng(p:K, u:b) "
format_alt = " $ip "
missing_format = ""
inactive_format = ""
theme_overrides.idle_bg = "#a3be86"
theme_overrides.idle_fg = { link = "idle_bg" }

[[block]]
block = "net"
device = "wlan0"
format = " $icon ^icon_net_down{$speed_down.eng(p:K, u:b)} ^icon_net_up $speed_up.eng(p:K, u:b) "
format_alt = " $ssid $signal_strength $ip "
missing_format = ""
inactive_format = ""
theme_overrides.idle_bg = "#a3be86"
theme_overrides.idle_fg = { link = "idle_bg" }

[[block]]
block = "net"
device = "gpd0"
format = " $icon VPN "
missing_format = ""
theme_overrides.idle_bg = "#3b4252"

[[block]]
device = "BAT0"
block = "battery"
format = " $icon $percentage "
missing_format = ""
empty_format = ""

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:2))|} "
theme_overrides.idle_bg = "#3b4252"

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
mappings = { "English (US)" = "🇺🇸", "Ukrainian (N/A)" = "🇺🇦" }
theme_overrides.idle_bg = "#3b4252"

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(format:'%b %d, %H:%M') "
