[theme]
theme = "nord-dark"

[theme.overrides]
idle_fg = "#d8dee9"
separator_bg = { link = "idle_bg" }
separator_fg = { link = "idle_fg" }
separator = " "

[icons]
icons = "material-nf"

[[block]]
block = "focused_window"
format = " $title.str(max_width:70) | "

[[block]]
block = "sound"
max_vol = 100
device_kind = "sink"
headphones_indicator = true
theme_overrides.idle_bg = { link = "info_bg" }
theme_overrides.idle_fg = { link = "info_fg" }

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "sound"
max_vol = 100
device_kind = "source"
theme_overrides.idle_bg = { link = "info_bg" }
theme_overrides.idle_fg = { link = "info_fg" }
theme_overrides.warning_fg = { link = "idle_fg" }
theme_overrides.warning_bg = { link = "idle_bg" }

[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "privacy"

[[block.driver]]
name = "pipewire"
display = "nickname"
exclude_input = ["capture.noise_suppressor", "capture.shure_mv7_for_podcasts"]

[[block.driver]]
name = "v4l"

[[block]]
block = "net"
device = "enp38s0"
format = " $icon  ^icon_net_down$speed_down.eng(p:K, u:b, w:3) ^icon_net_up$speed_up.eng(p:K, u:b, w:3) "
format_alt = " $ip "
missing_format = ""
inactive_format = ""
theme_overrides.idle_bg = { link = "good_bg" }
theme_overrides.idle_fg = { link = "idle_bg" }

[[block]]
block = "net"
device = "wlan0"
format = " $icon  ^icon_net_down$speed_down.eng(p:K, u:b, w:3) ^icon_net_up$speed_up.eng(p:K, u:b, w:3) "
format_alt = " $ssid $signal_strength $ip "
missing_format = ""
inactive_format = ""
theme_overrides.idle_bg = { link = "good_bg" }
theme_overrides.idle_fg = { link = "idle_bg" }

[[block]]
block = "net"
device = "gpd0"
format = " $icon VPN "
missing_format = ""

[[block]]
device = "BAT0"
block = "battery"
format = " $icon $percentage "
missing_format = ""
empty_format = ""

[[block]]
block = "notify"
format = " $icon {($notification_count.eng(w:2))|} "

[[block]]
block = "keyboard_layout"
driver = "sway"
format = " $layout "
mappings = { "English (US)" = "\U0001F1FA\U0001F1F8", "Ukrainian (N/A)" = "\U0001F1FA\U0001F1E6" }

[[block]]
block = "time"
interval = 5
format = " $icon $timestamp.datetime(format:'%b %d, %H:%M') "
