let $VIMHOME=fnamemodify($MYVIMRC, ':h')
if has('win32') || has('win64')
    set rtp+=$VIMHOME/
endif

source $VIMHOME/vimrc.d/plugins.vim
source $VIMHOME/vimrc.d/general.vim
source $VIMHOME/vimrc.d/commands.vim
source $VIMHOME/vimrc.d/mapping.vim
source $VIMHOME/vimrc.d/languages.vim
